blog_DACS/blog_DACS/Controllers/QLPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using blog_DACS.Models;

namespace blog_DACS.Controllers
{
    public class QLPostsController : Controller
    {
        private readonly BlogcanhannContext _context;

        public QLPostsController(BlogcanhannContext context)
        {
            _context = context;
        }
        private async Task<bool> IsUser()
        {

            var currentUserId = GetLoggedInUserId();
            if (currentUserId != null)
            {
                var currentUser = await _context.Users.FindAsync(currentUserId);
                if (currentUser != null && currentUser.IdRole == 2)
                {
                    return true;
                }
            }
            return false;
        }
        private long GetLoggedInUserId()
        {
            // Lấy Id của người dùng từ session
            var userIdString = HttpContext.Session.GetString("userId");

            // Kiểm tra xem userIdString có giá trị không
            if (userIdString != null && long.TryParse(userIdString, out long userId))
            {
                return userId;
            }
            else
            {
                // Trả về một giá trị mặc định hoặc xử lý theo nhu cầu của bạn
                return 0;
            }
        }

        // GET: QLPosts
        public async Task<IActionResult> Index()

        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
                var blogcanhannContext = _context.Posts.Include(p => p.IdUserNavigation);
                return View(await blogcanhannContext.ToListAsync());
            }
        }

        // GET: QLPosts/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
                if (id == null)
                {
                    return NotFound();
                }

                var post = await _context.Posts
                    .Include(p => p.IdUserNavigation)
                    .FirstOrDefaultAsync(m => m.IdPost == id);
                if (post == null)
                {
                    return NotFound();
                }

                return View(post);
            }
        }

        // GET: QLPosts/Create
        public async Task<IActionResult> Create()

        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
                ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "IdUser");
                return View();
            }
        }

        // POST: QLPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPost,Title,ContentPost,CreatedAt,ImagePost,LastAccessedAt,ExistenceStatus,IsPublic,IdUser")] Post post, IFormFile image)
        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
              
                long currentUserId = GetLoggedInUserId();
                if (image != null && image.Length > 0)
                {
                    post.ImagePost = await SaveImage(image);
                }
                post.IdPost = _context.Posts.Max(p => p.IdPost) + 1;
                post.IdUser = currentUserId;
                post.CreatedAt = DateTime.Now;
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }
        private async Task<string> SaveImage(IFormFile image)
        {
            var imageName = $"{Guid.NewGuid().ToString()}{Path.GetExtension(image.FileName)}";
            var imagePath = Path.Combine("wwwroot/images", imageName);
            using (var fileStream = new FileStream(imagePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return imageName;
        }

        // GET: QLPosts/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
                if (id == null)
                {
                    return NotFound();
                }

                var post = await _context.Posts.FindAsync(id);
                if (post == null)
                {
                    return NotFound();
                }
                ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "IdUser", post.IdUser);
                return View(post);
            }
        }
  

        // POST: QLPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("IdPost,Title,ContentPost,CreatedAt,ImagePost,LastAccessedAt,ExistenceStatus,IsPublic,IdUser")] Post post)
        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
                if (id != post.IdPost)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(post);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!PostExists(post.IdPost))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "IdUser", post.IdUser);
                return View(post);
            }
        }

        // GET: QLPosts/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.IdUserNavigation)
                .FirstOrDefaultAsync(m => m.IdPost == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: QLPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (await IsUser())
            {

                return RedirectToAction("AccessDenied", "Default");
            }
            else
            {
                var post = await _context.Posts.FindAsync(id);
                if (post != null)
                {
                    _context.Posts.Remove(post);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        private bool PostExists(long id)
        {
            return _context.Posts.Any(e => e.IdPost == id);
        }

    }
}

blog_DACS/blog_DACS/Controllers/SearchController.cs
using blog_DACS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using blog_DACS.Models;
namespace blog_DACS.Controllers;
    public class SearchController : Controller
{

    private readonly BlogcanhannContext _context;

    public SearchController(BlogcanhannContext context)
    {
        _context = context;
    }

    public IActionResult Index(string keyword)
    {
        // Nếu từ khóa trống, trả về trang tìm kiếm trống
        if (string.IsNullOrEmpty(keyword))
        {
            return View();
        }

        // Tìm kiếm các bài viết có tiêu đề chứa từ khóa
        var posts = _context.Posts
            .Where(p => p.Title.Contains(keyword))
            .ToList();


        return View(posts);
    }
    public IActionResult Indexuser(string keyword)
    {
        // Nếu từ khóa trống, trả về trang tìm kiếm trống
        if (string.IsNullOrEmpty(keyword))
        {
            return View();
        }

        // Tìm kiếm các bài viết có tiêu đề chứa từ khóa
        var user = _context.Users
            .Where(p => p.FullName.Contains(keyword))
            .ToList();


        return View(user);
    }
    public IActionResult postAdmin(string keyword)
    {
        // Nếu từ khóa trống, trả về trang tìm kiếm trống
        if (string.IsNullOrEmpty(keyword))
        {
            return View();
        }

        // Tìm kiếm các bài viết có tiêu đề chứa từ khóa
        var posts = _context.Posts
            .Where(p => p.Title.Contains(keyword))
            .ToList();


        return View(posts);
    }
    public IActionResult UserAdmin(string keyword)
    {
        // Nếu từ khóa trống, trả về trang tìm kiếm trống
        if (string.IsNullOrEmpty(keyword))
        {
            return View();
        }

        // Tìm kiếm các bài viết có tiêu đề chứa từ khóa
        var user = _context.Users
            .Where(p => p.FullName.Contains(keyword))
            .ToList();


        return View(user);
    }
}

blog_DACS/blog_DACS/Views/Search/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout - Copy.cshtml";
}

<div class="table-responsive">
    <!-- Thêm class để làm cho bảng có thể cuộn -->
    <table class="table table-bordered table-hover">
        <!-- Thêm các class của Bootstrap -->
        <thead>
            <tr>
               
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

 
        @foreach (var post in Model)
        {
            
                <article class="postcard dark blue">
                    <a class="postcard__img_link" asp-action="Details"asp-controller="Posts" asp-route-id="@post.IdPost">
                        <img class="postcard__img" src="~/images/@post.ImagePost" width="" alt="Image Title" />
                    </a>
                    <div class="postcard__text">
                        <h1 class="postcard__title blue"><a asp-action="Details" asp-route-id="@post.IdPost">@post.Title</a></h1>
                        <div class="postcard__subtitle small">
                            <time>
                                <i class="fas fa-calendar-alt mr-2"></i>@post.CreatedAt
                            </time>
                        </div>
                        <div class="postcard__bar"></div>
                        <div class="postcard__preview-txt">@post.ContentPost</div>
                    </div>
                </article>
        }
  
        </tbody>
    </table>
</div>

blog_DACS/blog_DACS/Views/Search/Indexuser.cshtml
@model IEnumerable<blog_DACS.Models.User>
@{
    ViewData["Title"] = "Indexuser";
    Layout = "~/Views/Shared/_Layout - Copy.cshtml";
}

<div class="table-responsive">
    <!-- Thêm class để làm cho bảng có thể cuộn -->
    <table class="table table-bordered table-hover">
        <!-- Thêm các class của Bootstrap -->
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>
                        <a style="color: white; font-size: 20px">@user.FullName</a>

                </td>
                    <td>
                        <form method="post" asp-action="FollowUser" asp-controller="Profile">
                            <input type="hidden" name="idFollowing" value="@user.IdUser" />
                            <button type="submit" class="btn btn-primary">Follow</button>
                        </form>
                    </td>
                    <td>
                        
                        
                            <form method="post" asp-action="UnfollowUser" asp-controller="Profile">
                                <input type="hidden" name="idFollowing" value="@user.IdUser" />
                                <button type="submit" class="btn btn-danger">Unfollow</button>
                            </form>
                        
                      
                    </td>
                    <td>
                        <form method="post" asp-action="FavoriteUser" asp-controller="Profile">
                            <input type="hidden" name="idFavoriteUser" value="@user.IdUser" />
                            <button type="submit" class="btn btn-success">Favorite</button> <!-- Thêm class của Bootstrap -->
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

blog_DACS/blog_DACS/Views/Search/UserAdmin.cshtml
@model IEnumerable<blog_DACS.Models.User>
@{
    ViewData["Title"] = "UserAdmin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                Tên
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Gmail
            </th>
            <th>
                Năm sinh
            </th>
            <th>
                Gioi Tính
            </th>
            <th>
                Nơi sinh
            </th>
            <th>
                ngày tạo
            </th>
            <th>

            </th>
            <th>
                Trạng thái
            </th>
            <th>

            </th>
            <th>
                Vai trò
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => user.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.PlaceOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.CreatedAt)
                </td>
                <td>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.ExistenceStatus)
                </td>
                <td>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => user.IdRoleNavigation.RoleName)
                </td>
                <td>
                    @*  <a asp-action="Edit" asp-route-id="@item.IdUser">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdUser">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdUser">Delete</a> *@
                </td>
            </tr>
        }
    </tbody>
</table>

blog_DACS/blog_DACS/Views/Search/postAdmin.cshtml
@{
    ViewData["Title"] = "postAdmin";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


        @foreach (var item in Model)
        {
    <article class="postcard dark blue">
        <a class="postcard__img_link" asp-action="Details" asp-route-id="@item.IdPost">
            <img class="postcard__img" src="~/images/@item.ImagePost" width="150px" alt="Image Title" />
        </a>
        <div class="postcard__text">
            <h1 class="postcard__title blue"><a asp-action="Details" asp-controller="QLPosts" asp-route-id="@item.IdPost">@item.Title</a></h1>
            <div class="postcard__subtitle small">
                <time>
                    <i class="fas fa-calendar-alt mr-2"></i>@item.CreatedAt
                </time>
            </div>
            <div class="postcard__bar"></div>
            <div class="postcard__preview-txt">@item.ContentPost</div>
        </div>
    </article>
        }
    </tbody>
</table>