blog_DACS/blog_DACS/Controllers/QLCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using blog_DACS.Models;
using Microsoft.Extensions.Hosting;

namespace blog_DACS.Controllers
{
    public class QLCommentsController : Controller
    {
        private readonly BlogcanhannContext _context;

        public QLCommentsController(BlogcanhannContext context)
        {
            _context = context;
        }

        // GET: QLComments
        public async Task<IActionResult> Index()
        {
            var blogcanhannContext = _context.Comments.Include(c => c.IdPostNavigation).Include(c => c.IdUserNavigation);
            return View(await blogcanhannContext.ToListAsync());
        }

        // GET: QLComments/Details/5
        public async Task<IActionResult> Details(long? id, long? idPost)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.IdPostNavigation)
                .Include(c => c.IdUserNavigation)
                .FirstOrDefaultAsync(m => m.IdUser == id && m.IdPost ==idPost);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: QLComments/Create
        public IActionResult Create()
        {
            ViewData["IdPost"] = new SelectList(_context.Posts, "IdPost", "IdPost");
            ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "IdUser");
            return View();
        }

        // POST: QLComments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContentComment,CreatedAt,ParentComment,IdPost,IdUser")] Comment comment)
        {
            
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            ViewData["IdPost"] = new SelectList(_context.Posts, "IdPost", "IdPost", comment.IdPost);
            ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "IdUser", comment.IdUser);
            return View(comment);
        }

        // GET: QLComments/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["IdPost"] = new SelectList(_context.Posts, "IdPost", "Title", comment.IdPost);
            ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "Email", comment.IdUser);
            return View(comment);
        }

        // POST: QLComments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long idPost, long idUser, [Bind("IdPost,IdUser,ContentComment,CreatedAt,ParentComment")] Comment comment)
        {
            if (idPost != comment.IdPost || idUser != comment.IdUser)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.IdPost, comment.IdUser))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPost"] = new SelectList(_context.Posts, "IdPost", "Title", comment.IdPost);
            ViewData["IdUser"] = new SelectList(_context.Users, "IdUser", "Email", comment.IdUser);
            return View(comment);
        }

        // GET: QLComments/Delete/5
        public async Task<IActionResult> Delete(long? idPost, long? idUser)
        {
            if (idPost == null || idUser == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.IdPostNavigation)
                .Include(c => c.IdUserNavigation)
                .FirstOrDefaultAsync(m => m.IdPost == idPost && m.IdUser == idUser);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: QLComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteComfi(long idPost, long idUser)
        {
            var comment = await _context.Comments
                .FirstOrDefaultAsync(m => m.IdPost == idPost && m.IdUser == idUser);
            if (comment != null)
            {
                _context.Comments.Remove(comment);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }


        private bool CommentExists(long idPost, long idUser)
        {
            return _context.Comments.Any(e => e.IdPost == idPost && e.IdUser == idUser);
        }
    }
}

blog_DACS/blog_DACS/Views/QLComments/Create.cshtml
@model blog_DACS.Models.Comment

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ContentComment" class="control-label"></label>
                <input asp-for="ContentComment" class="form-control" />
                <span asp-validation-for="ContentComment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentComment" class="control-label"></label>
                <input asp-for="ParentComment" class="form-control" />
                <span asp-validation-for="ParentComment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPost" class="control-label"></label>
                <select asp-for="IdPost" class ="form-control" asp-items="ViewBag.IdPost"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdUser" class="control-label"></label>
                <select asp-for="IdUser" class ="form-control" asp-items="ViewBag.IdUser"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

blog_DACS/blog_DACS/Views/QLComments/Delete.cshtml
@model blog_DACS.Models.Comment

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContentComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContentComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPostNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPostNavigation.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUserNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUserNavigation.Email)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPost" />
        <input type="hidden" asp-for="IdUser" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

blog_DACS/blog_DACS/Views/QLComments/Details.cshtml
@model blog_DACS.Models.Comment

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Comment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContentComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContentComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParentComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParentComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPostNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPostNavigation.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUserNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUserNavigation.Email)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

blog_DACS/blog_DACS/Views/QLComments/Edit.cshtml
@model blog_DACS.Models.Comment

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ContentComment" class="control-label"></label>
                <input asp-for="ContentComment" class="form-control" />
                <span asp-validation-for="ContentComment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParentComment" class="control-label"></label>
                <input asp-for="ParentComment" class="form-control" />
                <span asp-validation-for="ParentComment" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IdPost" />
            <input type="hidden" asp-for="IdUser" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

blog_DACS/blog_DACS/Views/QLComments/Index.cshtml
@model IEnumerable<blog_DACS.Models.Comment>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Quản Lý bình luận</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                Nội dung
            </th>
            <th>
                Ngày tạo
            </th>
            <th>
                bình luận
            </th>
            <th>
               IdPost
            </th>
            <th>
                <p>Gmail</p>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ContentComment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentComment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdPostNavigation.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUserNavigation.Email)
            </td>
            <td>

                    <a asp-action="Delete" asp-controller="QLComments" asp-route-idUser="@item.IdUser" asp-route-idPost="@item.IdPost">Xóa</a>
            </td>
        </tr>
}
    </tbody>
</table>